--Explore all objects from database
select* from INFORMATION_SCHEMA.TABLES;

--Explore all columns from the database 
select* from INFORMATION_SCHEMA.COLUMNS
where table_name ='dim_customers';

--Explore all countries our customers comes from
select distinct country from [data warehouse analytics].[dbo].[gold.dim_customers];

--Explore all categories "the major divisions"
select distinct category,subcategory,product_name from [data warehouse analytics].[dbo].[gold.dim_products]
order by 1,2,3;

--Find the date of the first and the last order
--How many years of sales are available
select
min(order_date) first_date,
max (order_date) last_date,
DATEDIFF(year,min(order_date),max (order_date)) order_range_years,
DATEDIFF(month,min(order_date),max (order_date)) order_range_months
from [data warehouse analytics].[dbo].[gold.fact_sales];

--Find the youngest and the oldest customer 
select 
min(birthdate)oldest_birthdate,
max(birthdate)youngest_birthdate,
DATEDIFF(year,min(birthdate),GETDATE()) as oldest_age,
DATEDIFF(year,max(birthdate),GETDATE()) as youngest_age
from [data warehouse analytics].[dbo].[gold.dim_customers];

--Find the total sales 
select sum(sales_amount) as total_sales from [data warehouse analytics].[dbo].[gold.fact_sales];

--Find how many items are sold
select sum(quantity) as total_quantity from [data warehouse analytics].[dbo].[gold.fact_sales];

--Find average selling price
select avg (price) as avg_price from [data warehouse analytics].[dbo].[gold.fact_sales];

--Find the total number of products
select count (PRODUCT_name) as total_products from [data warehouse analytics].[dbo].[gold.dim_products];
select count (distinct PRODUCT_name) as total_products from [data warehouse analytics].[dbo].[gold.dim_products];

--Find the total number of orders
select count(order_number) as total_orders from [data warehouse analytics].[dbo].[gold.fact_sales];
select count(distinct order_number) as total_orders from [data warehouse analytics].[dbo].[gold.fact_sales];

--Find the total number of customers
select count(customer_id) as total_customers from [data warehouse analytics].[dbo].[gold.dim_customers];

--Find the total number of that has placed an order
select count(distinct customer_key) as total_customers from [data warehouse analytics].[dbo].[gold.fact_sales];

--Generate a report that shows all key metrics of the business
select'total sales' as measure_name,
sum(sales_amount) as measure_value from [data warehouse analytics].[dbo].[gold.fact_sales]
union all 
select'total quantity' as measure_name,
sum(quantity) as measure_value from [data warehouse analytics].[dbo].[gold.fact_sales]
union all
select'average_price' as measure_name,
avg(price) as measure_value from [data warehouse analytics].[dbo].[gold.fact_sales]
union all 
select'total Nr.products' as measure_name,
count(product_name) as measure_value from [data warehouse analytics].[dbo].[gold.dim_products]
union all
select'total Nr. orders' as measure_name,
count(distinct order_number) as measure_value from [data warehouse analytics].[dbo].[gold.fact_sales]
union all
select'total Nr. customers' as measure_name,
count(customer_key) as measure_value from [data warehouse analytics].[dbo].[gold.dim_customers]

--Find total customers by countries
select country,
count(customer_key) total_customers from [data warehouse analytics].[dbo].[gold.dim_customers]
group by country
order by total_customers desc;

--Find total customers by gendeer
select gender,
count(customer_key) total_customers from [data warehouse analytics].[dbo].[gold.dim_customers]
group by gender
order by total_customers desc; 

--Find total products by category
select category,
count(product_key) total_products from [data warehouse analytics].[dbo].[gold.dim_products]
group by category
order by total_products desc; 
--What is the average costs in each category 
select category,
avg(cost) as avg_costs from [data warehouse analytics].[dbo].[gold.dim_products]
group by category
order by avg_costs desc;

--What is the total revenue is generated by each category 
select sum(f.sales_amount)total_revenue,
p.category
from [data warehouse analytics].[dbo].[gold.fact_sales] f
left join [data warehouse analytics].[dbo].[gold.dim_products] p
on f.product_key=p.product_key
group by p.category
order by total_revenue;
--Find total revenue is generated by each customer
select sum(f.sales_amount)total_revenue,
c.customer_key,
c.first_name,
c.last_name
from [data warehouse analytics].[dbo].[gold.fact_sales] f
left join [data warehouse analytics].[dbo].[gold.dim_customers] c
on f.customer_key=c.customer_key
group by c.customer_key,c.first_name,
c.last_name
order by total_revenue;
--What is the distribution of sold items across countries
select sum(f.quantity)total_sold_items,
c.country
from [data warehouse analytics].[dbo].[gold.fact_sales] f
left join [data warehouse analytics].[dbo].[gold.dim_customers] c
on f.customer_key=c.customer_key
group by c.country
order by total_sold_items desc;

--which 5 products generate the highest revenue
select top 5
p.product_name, sum(f.sales_amount) total_revenue
from  [data warehouse analytics].[dbo].[gold.fact_sales] f
left join [data warehouse analytics].[dbo].[gold.dim_products] p
on f.product_key=p.product_key
group by p.product_name
order by total_revenue desc;

--what are the 5 worst_performing products in terms of sales
select top 5
p.product_name, sum(f.sales_amount) total_revenue
from  [data warehouse analytics].[dbo].[gold.fact_sales] f
left join [data warehouse analytics].[dbo].[gold.dim_products] p
on f.product_key=p.product_key
group by p.product_name
order by total_revenue asc;
